jira:
  base_url: https://neeteshrajoriya3.atlassian.net
  email: neetesh.rajoriya3@gmail.com
  api_token: ATATT3xFfGF0azlqtiCmL_nC_AQFJExHNQqOadsLZmAzmHPVosJ2QEnRNoa9b8cg3InjfsaCmX7ROR7FZLNRp5JtHRxqa7qBlDJJdfA7cippDFzyfHwk4OooJYbRkKWSYc6Ct_QnwXE-FyehVvoUJdymEugkwHk7h9Mz18FAjZYh6R9QsUH_r2E=BE469D73
  project_key: TEST
  search_jql: ORDER BY created DESC
  test_user_email: neetesh.rajoriya3@gmail.com
  project:
    name: AutomatedProject
    key: SAS
    lead_email: neetesh.rajoriya3@gmail.com
    issue:
      summary: Sample Issue
      description: This is a test issue.
  project_type_key:
    business:
      1: com.atlassian.jira-core-project-templates:jira-core-simplified-content-management
      2: com.atlassian.jira-core-project-templates:jira-core-simplified-document-approval
      3: com.atlassian.jira-core-project-templates:jira-core-simplified-lead-tracking
      4: com.atlassian.jira-core-project-templates:jira-core-simplified-process-control
      5: com.atlassian.jira-core-project-templates:jira-core-simplified-procurement
      6: com.atlassian.jira-core-project-templates:jira-core-simplified-project-management
      7: com.atlassian.jira-core-project-templates:jira-core-simplified-recruitment
      8: com.atlassian.jira-core-project-templates:jira-core-simplified-task-tracking
    service_desk:
      1: com.atlassian.servicedesk:simplified-it-service-management
      2: com.atlassian.servicedesk:simplified-general-service-desk-it
      3: com.atlassian.servicedesk:simplified-general-service-desk-business
      4: com.atlassian.servicedesk:simplified-external-service-desk
      5: com.atlassian.servicedesk:simplified-hr-service-desk
      6: com.atlassian.servicedesk:simplified-facilities-service-desk
      7: com.atlassian.servicedesk:simplified-legal-service-desk
      8: com.atlassian.servicedesk:simplified-analytics-service-desk
      9: com.atlassian.servicedesk:simplified-marketing-service-desk
      10: com.atlassian.servicedesk:simplified-design-service-desk
      11: com.atlassian.servicedesk:simplified-sales-service-desk
      12: com.atlassian.servicedesk:simplified-blank-project-business
      13: com.atlassian.servicedesk:simplified-blank-project-it
      14: com.atlassian.servicedesk:simplified-finance-service-desk
      15: com.atlassian.servicedesk:next-gen-it-service-desk
      16: com.atlassian.servicedesk:next-gen-hr-service-desk
      17: com.atlassian.servicedesk:next-gen-legal-service-desk
      18: com.atlassian.servicedesk:next-gen-marketing-service-desk
      19: com.atlassian.servicedesk:next-gen-facilities-service-desk
      20: com.atlassian.servicedesk:next-gen-general-it-service-desk
      21: com.atlassian.servicedesk:next-gen-general-business-service-desk
      22: com.atlassian.servicedesk:next-gen-analytics-service-desk
      23: com.atlassian.servicedesk:next-gen-finance-service-desk
      24: com.atlassian.servicedesk:next-gen-design-service-desk
    software:
      1: com.pyxis.greenhopper.jira:gh-simplified-agility-kanban
      2: com.pyxis.greenhopper.jira:gh-simplified-agility-scrum
      3: com.pyxis.greenhopper.jira:gh-simplified-basic
      4: com.pyxis.greenhopper.jira:gh-simplified-kanban-classic
      5: com.pyxis.greenhopper.jira:gh-simplified-scrum-classic
  project_api:
    GET_Get_all_projects: /rest/api/3/project
    POST_Create_project: /rest/api/3/project
    GET_Get_recent_projects: /rest/api/3/project/recent
    GET_Get_projects_paginated: /rest/api/3/project/search
    GET_Get_project: /rest/api/3/project/{projectIdOrKey}
    PUT_Update_project: /rest/api/3/project/{projectIdOrKey}
    DEL_Delete_project: /rest/api/3/project/{projectIdOrKey}
    POST_Archive_project: /rest/api/3/project/{projectIdOrKey}/archive
    POST_Delete_project_asynchronously: /rest/api/3/project/{projectIdOrKey}/delete
    POST_Restore_deleted_or_archived_project: /rest/api/3/project/{projectIdOrKey}/restore
    GET_Get_all_statuses_for_project: /rest/api/3/project/{projectIdOrKey}/statuses
    GET_Get_project_issue_type_hierarchy: /rest/api/3/project/{projectId}/hierarchy
    GET_Get_project_notification_scheme: /rest/api/3/project/{projectKeyOrId}/notificationscheme
  user_api:
    GET_Get_user: /rest/api/3/user
    POST_Create_user: /rest/api/3/user
    DEL_Delete_user: /rest/api/3/user
    GET_Bulk_get_users: /rest/api/3/user/bulk
    GET_Get_account_IDs_for_users: /rest/api/3/user/bulk/migration
    GET_Get_user_default_columns: /rest/api/3/user/columns
    PUT_Set_user_default_columns: /rest/api/3/user/columns
    DEL_Reset_user_default_columns: /rest/api/3/user/columns
    GET_Get_user_email: /rest/api/3/user/email
    GET_Get_user_email_bulk: /rest/api/3/user/email/bulk
    GET_Get_user_groups: /rest/api/3/user/groups
    GET_Get_all_users_default: /rest/api/3/users
    GET_Get_all_users: /rest/api/3/users/search
    user_email_for_creation: neet1221@yopmail.com

  issue_api:
    POST_Bulk_fetch_changelogs: /rest/api/3/changelog/bulkfetch
    GET_Get_events: /rest/api/3/events
    POST_Create_issue: /rest/api/3/issue
    PUT_Archive_issue(s)_by_issue_ID/key: /rest/api/3/issue/archive
    POST_Archive_issue(s)_by_JQL: /rest/api/3/issue/archive
    POST_Bulk_create_issue: /rest/api/3/issue/bulk
    POST_Bulk_fetch_issues: /rest/api/3/issue/bulkfetch
    GET_Get_create_issue_metadata: /rest/api/3/issue/createmeta
    GET_Get_create_metadata_issue_types_for_a_project: /rest/api/3/issue/createmeta/{projectIdOrKey}/issuetypes
    GET_Get_create_field_metadata_for_a_project_and_issue_type_id: /rest/api/3/issue/createmeta/{projectIdOrKey}/issuetypes/{issueTypeId}
    GET_Get_issue_limit_report: /rest/api/3/issue/limit/report
    PUT_Unarchive_issue(s)_by_issue_keys/ID: /rest/api/3/issue/unarchive
    GET_Get_issue: /rest/api/3/issue/{issueIdOrKey}
    PUT_Edit_issue: /rest/api/3/issue/{issueIdOrKey}
    DEL_Delete_issue: /rest/api/3/issue/{issueIdOrKey}
    PUT_Assign_issue: /rest/api/3/issue/{issueIdOrKey}/assignee
    GET_Get_changelogs: /rest/api/3/issue/{issueIdOrKey}/changelog
    POST_Get_changelogs_by_IDs: /rest/api/3/issue/{issueIdOrKey}/changelog/list
    GET_Get_edit_issue_metadata: /rest/api/3/issue/{issueIdOrKey}/editmeta
    POST_Send_notification_for_issue: /rest/api/3/issue/{issueIdOrKey}/notify
    GET_Get_transitions: /rest/api/3/issue/{issueIdOrKey}/transitions
    POST_Transition_issue: /rest/api/3/issue/{issueIdOrKey}/transitions
    PUT_Export_archived_issue(s): /rest/api/3/issues/archive/export

  new_project:
    assigneeType: PROJECT_LEAD
    description: Try to calculate the AI application, maybe it will input the primary
      panel!
    key: WQW
    name: WQER
    lead_AccountId: 712020:ca1ae7f1-3fce-4238-b039-fa6332bcd5d0
    projectTemplateKey: com.pyxis.greenhopper.jira:gh-simplified-agility-scrum
    projectTypeKey: software
    id: 10062


