jira:
  base_url: "https://neeteshrajoriya3.atlassian.net"
  email: "neetesh.rajoriya3@gmail.com"
  api_token: "ATATT3xFfGF0t2L3KNnxphW5dbD_AFIn9ggUhGSP3M8EQnM90_4K6nSMweTHvPbGJ1eUwFIByXbAYmw9typ3r5hQjhJoqdSqUV_UdrD2GDhwyd38Ruixq_rhvehDM0eNDZ07Ot-it-jwI1C7WLeh6PohTa5jwr7TkcKTW27z_L7f6DXJZodUuPM=C05CB2DD"
  project_key: "TEST"
  search_jql: "ORDER BY created DESC"
  test_user_email: "neetesh.rajoriya3@gmail.com"
  project:
    name: "AutomatedProject"
    key: "XML"
    lead_email: "neetesh.rajoriya3@gmail.com"
    issue:
      summary: "Sample Issue"
      description: "This is a test issue."
  project_api:
    GET_Get_all_projects: "/rest/api/3/project"
    POST_Create_project: "/rest/api/3/project"
    GET_Get_recent_projects: "/rest/api/3/project/recent"
    GET_Get_projects_paginated: "/rest/api/3/project/search"
    GET_Get_project: "/rest/api/3/project/"
    PUT_Update_project: "/rest/api/3/project/{projectIdOrKey}"
    DEL_Delete_project: "/rest/api/3/project/{projectIdOrKey}"
    POST_Archive_project: "/rest/api/3/project/{projectIdOrKey}/archive"
    POST_Delete_project_asynchronously: "/rest/api/3/project/{projectIdOrKey}/delete"
    POST_Restore_deleted_or_archived_project: "/rest/api/3/project/{projectIdOrKey}/restore"
    GET_Get_all_statuses_for_project: "/rest/api/3/project/{projectIdOrKey}/statuses"
    GET_Get_project_issue_type_hierarchy: "/rest/api/3/project/{projectId}/hierarchy"
    GET_Get_project_notification_scheme: "/rest/api/3/project/{projectKeyOrId}/notificationscheme"
  user_api:
    GET_Get_user: "/rest/api/3/user"
    POST_Create_user: "/rest/api/3/user"
    DEL_Delete_user: "/rest/api/3/user"
    GET_Bulk_get_users: "/rest/api/3/user/bulk"
    GET_Get_account_IDs_for_users: "/rest/api/3/user/bulk/migration"
    GET_Get_user_default_columns: "/rest/api/3/user/columns"
    PUT_Set_user_default_columns: "/rest/api/3/user/columns"
    DEL_Reset_user_default_columns: "/rest/api/3/user/columns"
    GET_Get_user_email: "/rest/api/3/user/email"
    GET_Get_user_email_bulk: "/rest/api/3/user/email/bulk"
    GET_Get_user_groups: "/rest/api/3/user/groups"
    GET_Get_all_users_default: "/rest/api/3/users"
    GET_Get_all_users: "/rest/api/3/users/search"